---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: human-resources
  description: Human Resources domain - Employee lifecycle, payroll, and talent management
  tags:
    - hr
    - people-operations
spec:
  owner: hr-leadership-team

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: hr-platform-team
  description: Team responsible for HCM platform development and maintenance
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: payroll-team
  description: Team managing payroll services
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: security-team
  description: Security and authentication team
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform and infrastructure team
spec:
  type: team
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: hr-leadership-team
  description: HR Leadership and strategy team
spec:
  type: team
  children: []
