---
# SYSTEM
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: hcm-system
  description: Human Capital Management System
  tags:
    - hr
    - employee-management
spec:
  owner: hr-platform-team

---
# 1. APPLICATION COMPONENT
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hcm-application
  description: HCM Application - Employee management web application
  tags:
    - java
    - spring-boot
    - web-app
  annotations:
    github.com/project-slug: i-hsingh/hcm-application
spec:
  type: service
  lifecycle: production
  owner: hr-platform-team
  system: hcm-system
  dependsOn:
    - resource:default/hcm-database
    - resource:default/hcm-infrastructure

---
# 2. DATABASE RESOURCE
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hcm-database
  description: PostgreSQL database for HCM data storage
  tags:
    - postgresql
    - database
    - rds
spec:
  type: database
  lifecycle: production
  owner: hr-platform-team
  system: hcm-system
  dependsOn:
    - resource:default/hcm-infrastructure

---
# 3. INFRASTRUCTURE RESOURCE
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hcm-infrastructure
  description: AWS infrastructure (VPC, EKS, networking)
  tags:
    - aws
    - kubernetes
    - infrastructure
spec:
  type: infrastructure
  lifecycle: production
  owner: platform-team
  system: hcm-system
